image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies
    # Update base env with packages from environment.yml
    # Run on initial workspace start if no prebuild available
    init: |
      conda env update -n base --file environment.yml
    # Run on every workspace start
    command: |
      echo 'Installing TRF2GFF in interactive mode.'
      pip3 install -e .

vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python
    - oderwat.indent-rainbow
