name: trf2gffdev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.12
  - bioconda::trf
  - pip
  - pip:
      - black
      - setuptools_scm
      - build
      - twine
